name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-go-checks:
    uses: yottta/github-workflows/.github/workflows/checks.yaml@main
    with:
      go-enabled: true
      go-build-pattern: './...'
      go-test-pattern: './...'
