name: Release new version

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-go-checks:
    uses: yottta/github-workflows/.github/workflows/goreleaser.yaml@main
    secrets:
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.PASSPHRASE }}
      release_github_token: ${{ secrets.GITHUB_TOKEN }}
